name: giltezy_2ndproject
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  google_sign_in: ^6.1.4
 
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  auth_buttons: ^1.0.1+4
  smooth_page_indicator: ^1.1.0
  google_nav_bar: ^5.0.6
  babylonjs_viewer: ^1.2.1
  avatar_glow: ^2.0.2
  carousel_slider: ^4.2.1
  # sliding_up_panel: ^2.0.0+1
  # google_fonts: ^5.1.0
 
  flutter_cache_manager: ^3.3.1
  badges: ^3.1.1
  
  flutter_slidable: ^3.0.0
  imageview360: ^1.3.0
  cart_stepper: ^4.1.2
  flutter_add_to_cart_button: ^1.1.0
  pushable_button: ^0.0.2
  flutter_animated_button: ^2.0.3
  timeline_tile: ^2.0.0
  like_button: ^2.0.5
  image_picker: ^1.0.2
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.2.6
  iconify_flutter: ^0.0.5
  flip_card: ^0.7.0
  
  bottom_bar_with_sheet: ^2.4.0
  motion_toast: ^2.7.8
  readmore: ^2.2.0
  animated_text_kit: ^4.2.2
  cool_alert: ^2.0.1
  multi_state_button: ^1.1.3
  hidable: ^1.0.5
  flutter_scrolling_fab_animated: ^0.1.4
  flutter_spinkit: ^5.2.0
  top_snackbar_flutter: ^3.1.0
  flutter_riverpod: ^2.4.0
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  flutter_easyloading: ^3.0.5
  draggable_home: ^1.0.5
  flashy_tab_bar2: ^0.0.6
  dot_navigation_bar: ^1.0.2
  animations: ^2.0.8
  scroll_page_view: ^1.0.2
  scroll_to_hide_bottom_navigation_bar: ^0.0.1
  flutter_stripe: ^9.4.0
  razorpay_flutter: ^1.3.5
 
 
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/shiwa-id-Uae7ouMw91A-unsplash.jpg
    
    - assets/images/max-whitehead-nRKzAy4w6mE-unsplash.jpg
    - assets/images/anh-nhat-yqcloMb3Abw-unsplash.jpg
    - assets/images/thai-nguyen-dcSJWwdyAl8-unsplash (1).jpg
    - assets/images/walling-52H5Nfi5WiE-unsplash.jpg
    - assets/images/reallogo.png
    - assets/images/martin-engel-44zXCbDd2WQ-unsplash.jpg
    - assets/images/imagesnew.jpg
    - assets/images/giltezy.jpg
    - assets/images/background.jpg
    - assets/images/Screenshot 2023-08-12 061206.png
    - assets/images/Screenshot 2023-08-12 061246.png
    - assets/images/Screenshot 2023-08-12 061315.png
    - assets/images/Screenshot 2023-08-12 061337.png
    - assets/images/image_-_2023-06-02T162012.132.webp
    - assets/images/samsung-galaxy-s21-smartphones.jpg
    - assets/images/v585-aew-28-devicemockup.jpg
    - assets/images/ramal-wickramasinghe-OjMyiwfviQ4-unsplash.jpg
    - assets/images/anh-nhat-PdALQmfEqvE-unsplash.jpg
    - assets/images/787.jpg
    - assets/images/Xiaomi-logo.jpg
    - assets/images/Vivo-logo.jpg
    - assets/images/Samsung-logo.jpg
    - assets/images/Google__G__Logo.png
    - assets/images/OnePlus-logo.jpg
    - assets/images/Apple-Logo.png
    - assets/images/LG-Logo-1995.jpg
    - assets/images/Huawei-logo.jpg
    - assets/images/Nokia-Logo.png
    - assets/images/Lenovo-logo.jpg
    - assets/images/Screenshot 2023-08-07 010809.png
    - assets/images/OPPO-logo.jpg
  
    - assets/images/XGehZ_9v_400x400.jpg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
